server:
  servlet:
    context-path: /auth-service
  port: 8090
spring:
  application:
    name: auth-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwt-set-uri: https://www.googleapis.com/oauth2/v3/certs