server:
  servlet:
    context-path: /auth-service
  port: 8090
spring:
  application:
    name: auth-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://accounts.google.com
#          jwt-set-uri: https://www.googleapis.com/oauth2/v3/certs

app:
  privateKey: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9